### ISSUE TITLE
compare with not working

### ISSUE THREAD

**Issue by gg4u** [DougTy/sublime-compare-side-by-side#17] opened 2016-12-17 12:46 UTC
Hi, just installed the packacke.
I see compare with option on right-click menu, but does not trigger anything, nor compare with active tag.

What could be the issue? maybe a missing configuration?

**Comment by DougTy** [comment] 2016-12-19 06:53
Try hitting Ctrl+~ to open the console, are there any errors there? Also, are you on Sublime Text 2 or 3?

**Comment by DougTy** [comment] 2017-01-09 13:37
As you haven't responded in a while & I cannot reproduce any error, I'll assume you no longer need help and will close this issue. Please let me know if the problem persists and I'll reopen. Thanks.

**Closed by DougTy** 2017-01-09 13:37 UTC
