### ISSUE TITLE
Compare breaks when upgrading to the latest ST3

### ISSUE THREAD

**Issue by jadami10** [DougTy/sublime-compare-side-by-side#31] opened 2017-09-16 14:57 UTC
```
Traceback (most recent call last):
  File "sbs_compare in /Users/jadami/Library/Application Support/Sublime Text 3/Installed Packages/Compare Side-By-Side.sublime-package", line 527, in on_click
  File "sbs_compare in /Users/jadami/Library/Application Support/Sublime Text 3/Installed Packages/Compare Side-By-Side.sublime-package", line 483, in create_comparison
  File "sbs_compare in /Users/jadami/Library/Application Support/Sublime Text 3/Installed Packages/Compare Side-By-Side.sublime-package", line 131, in generate_colour_scheme
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError(error)
OSError: resource not found
```

Manually picking the same color scheme in `Preferences > Color Scheme...` fixed it.

**Comment by DougTy** [comment] 2017-09-16 21:05
I'll try and take a look at this tonight. Thanks for bringing this to my attention.

**Comment by DougTy** [comment] 2017-09-16 22:36
I can't seem to reproduce this on Linux, and suspect it may be something specific to the colour scheme you're using, or perhaps some other plugin that's overriding it. The error seems to come from when we try to load the current colour scheme so we can append our own colours on to it--it's not being found for one reason or another.

1. What's `color_scheme` set to in `Preferences > Settings`?

2. If you hit `Ctrl`+`~` and paste this in, what's the result?
`view.settings().get( 'color_scheme' )`

Thanks.

**Comment by marmor7** [comment] 2017-09-17 12:10
Happened to me as well, was fixed by selecting to already selected color scheme.

color_scheme: 

> (default) "Packages/Color Scheme - Default/Monokai.tmTheme",
> (user) "Packages/Color Scheme - Default/Breakers.tmTheme"

Running from the main screen:
> view.settings().get( 'color_scheme' )
'Packages/Color Scheme - Default/Breakers.tmTheme'

Running from the Compare screen:
> view.settings().get( 'color_scheme' )
'Packages/User/SBSCompare.tmTheme'

**Comment by jadami10** [comment] 2017-09-17 22:58
color_scheme
```
(default) "color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",
(user) "color_scheme": "Packages/Color Scheme - Default/Mariana.tmTheme",
```
Running from the main screen:
```
>>> view.settings().get( 'color_scheme' )
'Packages/Color Scheme - Default/Mariana.tmTheme'
```
Running from the compare screen:
```
>>> view.settings().get( 'color_scheme' )
'Packages/User/SBSCompare.tmTheme'
```
Running Sublime 3.0 build 3143 (recently updated from 2.X)
On macOS Sierra 10.12.6

**Comment by DougTy** [comment] 2017-09-17 23:18
Cheers for the info.

It looks like nothing else is overriding the theme, so that rules out that possible cause.

Trying it out with the themes you're using (Mariana and Breakers), I am however still unable to reproduce the issue. I'm wondering if it may be an OSX specific thing--in which case I unfortunately do not have any access to an OSX machine to test.

Do you have to manually re-select the colour scheme after every comparison, or just every time you open Sublime? Or does manually re-selecting it once fix the issue permanently, even after restarting?

**Comment by jadami10** [comment] 2017-09-17 23:30
Now that I've set it manually, I can't reproduce it at all. It could very well be OSX specific. The only strange thing I notice is; if I remove the color scheme from my user settings file, the sublime theme updates automatically after saving the settings file. But the next compare I run will display with the old theme and does not update until after I click "ok" on the pop-up with the compare stats. I feel like the sublime update is unsetting some default setting.

I believe in
```
current_scheme = view.settings().get( 'color_scheme' )
```
you could supply some default color_scheme. That way maybe the issue users will see is the wrong theme in the compare window rather than nothing.

**Comment by DougTy** [comment] 2017-09-17 23:51
Good idea. I've added a fallback blank colour scheme to (hopefully) prevent this from being an issue for others. An alert will tell users how to fix it.

Thanks for your help with this!

**Closed** 2017-09-17 23:50 UTC
Labels: bug, more info needed

**Comment by stevage** [comment] 2018-05-24 05:00
I just ran into this, on OSX Sierra. Switching to another color scheme and back (as suggested above) worked.
