### ISSUE TITLE
Diff summary is illogical

### ISSUE THREAD

**Issue by aaaxx** [DougTy/sublime-compare-side-by-side#28] opened 2017-08-25 23:26 UTC
I'm always kind of baffled when the summary window pops up. The problem is that you sum the differences in both the old and the new file, essentially doubling the amount of edits, when logically each pair of differences is a single modification, becasue modifications, by definition, can only happen in the new file.

Another thing is, intra-line modifications shouldn't be counted as removed or added lines.

So, here's how I believe it should work:

- for intra-line modifications, `numIntra = len( subHighlightB )`
- for lines removed, `len( highlightA ) - len( subHighlightA )`
- for lines added, `len( highlightB ) - len( subHighlightB )`
- for line differences total, take the larger one of `len( highlightA )` and `len( highlightB )`

And note that this is still not entirely true, because it reports any fully modified line (i.e., a "full-line intra-line modification") as a removal plus addition, which I don't think it logically is. When I think of a _removed_ line, I think of a line that was completely cut out from the file, not just overwritten; the same goes for an _added_ line. But for this, you'd have to change the code to consider full line modifications the same as intra-line modifications, and I'll leave that for a separate discussion.

Oh, and one more thing: maybe consider renaming "## intra-line modifications" to "## lines modified". It aligns it with the "lines removed" / "lines added" pattern (and while you're at it, make the last one "## lines different in total"). Also, it's probably easier for non-native speakers.

**Comment by hadrielk** [comment] 2017-08-28 18:22
Yeah I agree the double-counting part is really wrong.
I also agree that intraline modifications should not be counted as removed+added, but instead just counted separately.
But for the "full line modification" I think it should be counted as a remove+add, because that's what most other tools count it as I think. Otherwise you get into weird situations, like one line getting removed but in its places 6 lines are added - is that 1 full line modification and 5 adds?

**Comment by DougTy** [comment] 2017-08-28 20:26
Yeah, you're right about the intraline modification count, as I'm fairly certain it's not possible to have an intraline modification on one side but not the other, so this is effectively being doubled. Please feel free to make a pull request for this @aaaxx 

However lines added and removed should definitely stay as they are now. The issue is that there's no such thing as an "overwritten" line. Any line not present in the to-file is considered a removal, and any line not present in the from-file is considered an addition. If two consecutive lines share enough commonalities, then it's marked as containing an intraline difference. A line that's been fully replaced will always be counted as a complete removal and subsequent addition. This is how all diffing tools work to the best of my knowledge, and I do not believe it's possible to change this behaviour with the diff library the plugin uses internally.

I disagree with removing the number of intraline differences from lines added and removed, as lines containing intraline differences are still technically removals and additions. The intraline aspect is just on top of that. [GitHub also treats it like this](https://github.com/DougTy/sublime-compare-side-by-side/commit/43d8dcb39ef2a87b43906194a588d68f28931f10#diff-0cdd8fa62d6485f699cf7c203f137d02L269)--hover over the green and red boxes at the top left of that file, then count the number of red lines. Despite the majority of "removed" lines containing only intraline differences, they are being still counted as removed. I would prefer not to do things differently from the standard.

**Comment by DougTy** [comment] 2017-08-29 06:02
Had some extra time tonight to quickly fix the intraline modification count myself. In the future please do not hesitate to send PRs, they are very much appreciated. I'd be happy to license the code under MIT or something similar if it makes it easier to contribute. (@hadrielk, what do you think about this? I feel I need your permission since some of this code is yours now too.)

**Closed by DougTy** 2017-08-29 06:02 UTC

**Comment by hadrielk** [comment] 2017-08-29 16:41
You don't need my permission, but sure MIT or BSD or even WTFPL is fine by me. :)
